### ISSUE TITLE
Filename Parsing Gives Incorrect Results

### ISSUE THREAD

**Issue by bpepple** [ajslater/comicfn2dict#1]
Was playing around with you library and it appears to stumble a bit when the series name contains hyphens instead of backslashes in the filename like the following:

```'Batman - Superman - World's Finest 022 (2024) (Webrip) (The Last Kryptonian-DCP).cbz```

This filename produces the following result which is incorrect:
```{'ext': 'cbz', 'issue': '022', 'remainders': ("World's Finest", '(The Last Kryptonian-DCP)'), 'scan_info': 'Webrip', 'series': 'Batman', 'title': 'Superman', 'year': '2024'}```

The expected result should be:
```{'ext': 'cbz', 'issue': '022', 'remainders': '(The Last Kryptonian-DCP)', 'scan_info': 'Webrip', 'series': "Batman - Superman - World's Finest", 'year': '2024'}```

**Comment by ajslater** [comment]
Hey big thanks for this. It caused me to re-evaluate my philosophy of breaking tokens by the `-` character and lead to some big improvements. This test case now passes with [version 0.2.0](https://github.com/ajslater/comicfn2dict/releases/tag/v0.2.0)
